"""Uploaded-paper handling for the HTTP API.

Upload and run submission are separate HTTP requests, so the extraction is
written to disk under a generated id and referenced by that id when a run is
started. Keeping it only in process memory would lose it between requests and
would make a second API worker unable to consume it.

The raw PDF is disposable and survives only until extraction completes. The
bounded extraction remains in this pending store long enough for a later run
request and is pruned by age. Once a run starts, its durable RunSpec carries a
separate frozen copy under the run retention policy.
"""

from __future__ import annotations

import json
import re
import shutil
import time
import uuid
from pathlib import Path

from academic_agent.run_output import DEFAULT_OUTPUT_ROOT

# Uploads and their extractions live outside the per-run directories: a paper
# may be uploaded and never run, and a run directory should describe a run.
PAPERS_ROOT = DEFAULT_OUTPUT_ROOT / "_papers"

# This one ceiling is shared by the streaming request reader and the persisted
# payload check. Larger PDFs are almost always scanned images, which the text
# extractor cannot use anyway.
MAX_UPLOAD_BYTES = 50 * 1024 * 1024

# An extraction is only useful until the run that consumes it starts. A day is
# generous for that and keeps a stale upload from lingering indefinitely.
_MAX_AGE_SECONDS = 24 * 60 * 60
# Paper ids are bearer capabilities between two requests. The old 12-hex
# suffix provided only 48 random bits, despite the id being the only
# credential for BYOK uploads. Accept only full-entropy generated ids rather
# than treating "not path traversal" as equivalent to "our capability".
_PAPER_ID_PATTERN = re.compile(r"paper-[0-9a-f]{32}")
_OWNER_FILE = ".owner"


class PaperNotFound(Exception):
    """Raised for an unknown or expired paper_id."""


class PaperTooLarge(Exception):
    """Raised when an upload exceeds MAX_UPLOAD_BYTES."""


class PaperNotAPdf(Exception):
    """Raised when an upload does not begin with the PDF signature."""


def _is_valid_paper_id(paper_id: str) -> bool:
    """Accept only capabilities generated by create_paper_id()."""
    return (
        isinstance(paper_id, str)
        and _PAPER_ID_PATTERN.fullmatch(paper_id) is not None
    )


def paper_dir(paper_id: str) -> Path:
    return PAPERS_ROOT / paper_id


def create_paper_id() -> str:
    return f"paper-{uuid.uuid4().hex}"


#: Every PDF starts with this. Checked because the filename and the declared
#: content type both come from the client, and the file is handed to a native
#: parser afterwards — a renamed archive or image should be refused here
#: rather than by pypdfium2 several layers in.
_PDF_SIGNATURE = b"%PDF-"


def save_upload(data: bytes, *, owner: str | None = None) -> tuple[str, Path]:
    """Persist an uploaded PDF. Returns (paper_id, pdf_path)."""
    if not data.startswith(_PDF_SIGNATURE):
        raise PaperNotAPdf(
            "The uploaded file does not look like a PDF (missing %PDF- header)."
        )
    if len(data) > MAX_UPLOAD_BYTES:
        raise PaperTooLarge(
            f"{len(data) / 1024 / 1024:.1f} MB exceeds the "
            f"{MAX_UPLOAD_BYTES // 1024 // 1024} MB limit"
        )

    paper_id = create_paper_id()
    directory = paper_dir(paper_id)
    directory.mkdir(parents=True, exist_ok=True)

    pdf_path = directory / "paper.pdf"
    try:
        # Store only the one-way owner id already used for runs, never the
        # access code. An absent marker deliberately means an ownerless BYOK
        # capability, not a paper available to every configured code.
        if owner is not None:
            (directory / _OWNER_FILE).write_text(owner, encoding="utf-8")
        pdf_path.write_bytes(data)
    except OSError:
        # A half-created capability must not remain discoverable by a later
        # request, especially when the owner marker was the write that failed.
        shutil.rmtree(directory, ignore_errors=True)
        raise
    return paper_id, pdf_path


def _read_owner(directory: Path) -> str | None:
    marker = directory / _OWNER_FILE
    if not marker.exists():
        return None
    try:
        owner = marker.read_text(encoding="utf-8").strip()
    except OSError as exc:
        # Unreadable ownership is a denial, never permission to fall back to
        # the ownerless capability path.
        raise PaperNotFound("Paper ownership metadata is unreadable") from exc
    if not owner:
        # An existing blank marker is corruption, not evidence that the upload
        # was created through the ownerless BYOK capability path.
        raise PaperNotFound("Paper ownership metadata is unreadable")
    return owner


def discard(paper_id: str) -> None:
    """Remove an upload and anything stored beside it. Never raises.

    For the extraction that failed: the PDF has already been written by then,
    and nothing downstream can ever use it — no paper_id was returned, so no
    run can reference it. Left in place it sat on the server for a full day
    waiting for the pruner, which is a day of holding someone's unpublished
    paper in exchange for an error message.

    Best-effort because the caller is already on an error path and is about to
    report a more useful failure than this one.
    """
    if not _is_valid_paper_id(paper_id):
        return
    shutil.rmtree(paper_dir(paper_id), ignore_errors=True)


def save_extraction(paper_id: str, extraction: dict) -> Path:
    """Atomically store extraction data, then remove the raw upload.

    The worker consumes extraction.json, never paper.pdf. Keeping the raw PDF
    for the 24-hour pending-upload window after extraction succeeded retained
    unpublished material without a runtime need. The replacement must become
    durable first; otherwise a storage failure would delete the only input
    from which the extraction could be retried.
    """
    if not _is_valid_paper_id(paper_id):
        raise PaperNotFound(f"Invalid paper id: {paper_id!r}")
    directory = paper_dir(paper_id)
    directory.mkdir(parents=True, exist_ok=True)
    path = directory / "extraction.json"
    temporary = directory / ".extraction.json.tmp"
    try:
        temporary.write_text(
            json.dumps(extraction, ensure_ascii=False, indent=2), encoding="utf-8"
        )
        temporary.replace(path)
        # original_name.txt is removed for pre-change directories too. New
        # uploads never store a client filename at all.
        for raw_name in ("paper.pdf", "original_name.txt"):
            (directory / raw_name).unlink(missing_ok=True)
    except OSError:
        try:
            temporary.unlink(missing_ok=True)
        except OSError:
            pass
        # If privacy cleanup cannot complete, do not return a capability that
        # implies the raw document was released according to the contract.
        discard(paper_id)
        raise
    return path


def load_extraction(paper_id: str) -> dict:
    """Read a stored extraction, raising PaperNotFound when absent."""
    if not _is_valid_paper_id(paper_id):
        raise PaperNotFound(f"Invalid paper id: {paper_id!r}")
    path = paper_dir(paper_id) / "extraction.json"
    if not path.exists():
        raise PaperNotFound(f"No extraction for paper id {paper_id}")
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise PaperNotFound(f"Extraction for {paper_id} is unreadable") from exc


def extraction_path_for_run(paper_id: str, *, owner: str | None = None) -> Path:
    """Validate a capability and return the worker's --paper-json path.

    Access-code uploads are bound to the same hashed owner as a run. Ownerless
    uploads remain bearer capabilities for BYOK/local mode, but a configured
    code cannot consume one merely because its id leaked.
    """
    if not _is_valid_paper_id(paper_id):
        raise PaperNotFound(f"Invalid paper id: {paper_id!r}")
    directory = paper_dir(paper_id)
    path = directory / "extraction.json"
    if not path.exists() or _read_owner(directory) != owner:
        # The same response for absence and ownership mismatch avoids turning
        # this lookup into a capability-existence oracle.
        raise PaperNotFound(f"No extraction for paper id {paper_id}")
    return path


def prune_old(max_age_seconds: int = _MAX_AGE_SECONDS) -> int:
    """Delete upload directories older than max_age_seconds.

    Best-effort: a directory that cannot be removed (open handle on Windows,
    permissions) is skipped rather than raising, since pruning runs on a timer
    and must not take down the caller.
    """
    if not PAPERS_ROOT.is_dir():
        return 0

    cutoff = time.time() - max_age_seconds
    removed = 0
    for directory in PAPERS_ROOT.iterdir():
        if not directory.is_dir():
            continue
        try:
            if directory.stat().st_mtime >= cutoff:
                continue
            shutil.rmtree(directory)
            removed += 1
        except OSError:
            continue
    return removed
